# Generated by Django 4.1.7 on 2023-02-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('image_url', models.CharField(max_length=200, verbose_name='Картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='webapp.category', verbose_name='Категория')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
